### ISSUE TITLE
"Pause when game window is inactive" is not working after ver 0.39.3

### ISSUE THREAD

**Issue by k24768** [cjsu/SMAPI#106]
In previous SMAPI, the game option worked properly with several mods loaded.
But after I switched to newer SMAPI, it did not pause even with the default mod only.
So I tested some different cases with mods and SMAPI version, SMAPI 0.39.2 is the newest one which the game option can work normally.

**Comment by k24768** [comment]
Hello, 
I tried to compile the source code, and do some version comparison and several trial and error.
I found this condition line in "Inheritance\SGame.cs" is no effect now.
`if ((paused /*|| !this.IsActive*/) && (options == null || options.pauseWhenOutOfFocus || paused))`

But it will pause properly if change the line to below:
`if (options.pauseWhenOutOfFocus && !IsActive)`

I hope this could help.

**Comment by Zoryn4163** [comment]
Hi there,
While you are correct, the solution would actually be to update the entire Update and Draw methods, but I don't believe this API is still in development as I myself do not have time and ClxS has been making a new API (that I believe is compatible with SMAPI Mods).
Apologies.

**Comment by k24768** [comment]
I found this issue is still remain in 0.40.1.1. Does any currently developers read this issue?

**Comment by Scyran** [comment]
Also not working for me on SMAPI-0.40.1.1-2.zip. Was working with the first 1.1 compatible .40.1 you put out.

**Comment by ClxS** [comment]
This is resolved in the latest release. We dont have any need to override the update calls anymore, so just removing that path solves it.
