### ISSUE TITLE
exception occured in XNA UpdateTick

### ISSUE THREAD

**Issue by Maaka2890** [cjsu/SMAPI#134]
Dear cjsu,

When I try to startup StardewModdingAPI.exe the following error is thrown over and over again. The game does start but crashes when I try to activate the CJB Cheat menu (press P).  I don't know if it is something I overlooked during install. I did follow the instructions and before the update everything worked fine.
Thank you for taking the time (and creating SMAPI) :)

Yours,

Maaka

```
An exception occured in XNA UpdateTick: System.MissingFieldException: Field not found: 'StardewValley.Game1.content'.
   at SMAPIChestLabelSystem.ChestModMainClass.EventUpdateTick(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at StardewModdingAPI.Events.GameEvents.InvokeUpdateTick() in Z:\Projects\SMAPI\src\StardewModdingAPI\Events\Game.cs:line 80
```

**Comment by Th3N3rdyGam3r** [comment]
Are you using STV 1.1? If so, most likely ChestLabelSystem isn't updated yet.

**Comment by Maaka2890** [comment]
Thanks for the quick reply. 
I checked STV is indeed version 1.1. I uninstalled the unsupported mods and downloaded the patches for the desired mods.
Problem was that I did not have an account to get the files from the forums.[http://community.playstarbound.com/threads/smapi-entos-home-of-abandoned-mods.125031/](url) 
Now I do, and all is well. 
Thanks for putting me on the correct (search) path ^^
