### ISSUE TITLE
Crash when browsing chests

### ISSUE THREAD

**Issue by Tyrindor** [cjsu/SMAPI#135]
I have gotten this crash ~5 times over the course of ~30 hours of playing when browsing chests, usually when putting an item into a chest.

Mods installed:
ChestPooling, CalendarAnywhere, FishingMod, GateOpener, GiftTasteHelper. Instant Geode, ToolCharging

Impossible to test if it's a mod or SMAPI itself due to it being pretty rare.

![a](https://cloud.githubusercontent.com/assets/855907/19094777/9a398b04-8a57-11e6-8c64-440e2a7e5eda.png)

**Comment by AdvizeGH** [comment]
Very likely caused by a mod. Also, SMAPI updated ~9 hours ago and the version you're using in this screenshot is outdated.

**Comment by Tyrindor** [comment]
I can't find the updated version anywhere?
https://github.com/cjsu/SMAPI/releases

I do not think it's caused by a mod, i contacted the chestpooling mod maker and he says it's not on his end. The other mods do not affect chests in any way.

**Comment by AdvizeGH** [comment]
It's an index out of range exception, meaning the code attempted to access an array/list index that was either less than 0 or larger than the size of the collection. Judging by the code found in StardewValley.Menus.InventoryMenu.hover(int, int, Item) I would hazard a guess that something has caused a discrepancy between the size of InventoryMenu.inventory and InventoryMenu.actualInventory.

This could possibly be a bug in the game itself (he does weird things where he converts an int to a string then back to an int to produce the inventory index), or there could be a mod that isn't adding/removing items from your inventory as gracefully as it should.

**Comment by Tyrindor** [comment]
Fixed, it was indeed Chest Pooling and he updated it.
